name: Rebuild on new Apache Tika tag (stable only)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"  # hourly

permissions:
  contents: write   # to commit the state file
  packages: write   # to push to GHCR

env:
  STATE_FILE: .github/upstream-tika-tag.txt
  PLATFORMS: linux/amd64  # add ",linux/arm64" for multi-arch

jobs:
  check-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Derive lowercase image name for GHCR
        id: img
        run: echo "image=ghcr.io/${GITHUB_REPOSITORY,,}" >> "$GITHUB_OUTPUT"

      # ✅ Get the latest "stable" tag — digits and dots only (e.g., 3.2.3)
      #    This skips pre-releases like 3.0.0-BETA2, 4.0.0-rc.1, etc.
      - name: Look up latest stable upstream tag
        id: latest
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          set -euo pipefail
          stable_tag="$(gh api repos/apache/tika/tags -F per_page=100 \
            --jq '[.[] | select(.name | test("^[0-9]+(\\.[0-9]+){1,3}$"))][0].name')"
          if [ -z "${stable_tag:-}" ] || [ "${stable_tag}" = "null" ]; then
            echo "Could not find a stable tag" >&2
            exit 1
          fi
          echo "latest=${stable_tag}" >> "$GITHUB_OUTPUT"
          echo "Latest stable upstream tag: ${stable_tag}"

      - name: Load previously seen tag
        id: prev
        run: |
          if [ -f "$STATE_FILE" ]; then
            printf "prev=%s\n" "$(cat "$STATE_FILE")" >> "$GITHUB_OUTPUT"
          else
            echo "prev=" >> "$GITHUB_OUTPUT"
          fi

      - name: Decide whether to build
        id: decide
        run: |
          if [ "${{ steps.latest.outputs.latest }}" != "${{ steps.prev.outputs.prev }}" ]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
            echo "New stable tag detected: ${{ steps.latest.outputs.latest }}"
          else
            echo "changed=false" >> "$GITHUB_OUTPUT"
            echo "No new stable tag; skipping build."
          fi

      - name: Log in to GHCR
        if: steps.decide.outputs.changed == 'true'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker metadata (tags/labels)
        if: steps.decide.outputs.changed == 'true'
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ steps.img.outputs.image }}
          tags: |
            type=raw,value=latest
            type=raw,value=${{ steps.latest.outputs.latest }}

      - name: Set up QEMU
        if: steps.decide.outputs.changed == 'true'
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        if: steps.decide.outputs.changed == 'true'
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        if: steps.decide.outputs.changed == 'true'
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: ${{ env.PLATFORMS }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # If you adopted ARG TIKA_TAG in your Dockerfile, pass it here:
          # build-args: |
          #   TIKA_TAG=${{ steps.latest.outputs.latest }}

      - name: Save latest seen stable tag (commit state)
        if: steps.decide.outputs.changed == 'true'
        run: |
          echo "${{ steps.latest.outputs.latest }}" > "$STATE_FILE"
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add "$STATE_FILE"
          git commit -m "ci: track apache/tika stable tag ${{ steps.latest.outputs.latest }} [skip ci]"
          git push